<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dlio</name>
  <version>0.0.1</version>
  <description>dlio</description>
  <maintainer email="bryan.chang@berkeley.edu">Bryan Chang</maintainer>
  <author email="bryan.chang@berkeley.edu">Bryan Chang</author>
  <author email="logankm@berkeley.edu">Logan Kinajil-Moran</author>
  <license>LGPLv3</license>

  <depend>gicp_localization</depend>
  <depend>dlio_input_adapter</depend>
  <depend>glim</depend>
  <depend>glim_ext</depend>
  <depend>glim_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
